# Generated by Django 5.1.7 on 2025-04-08 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentassessment",
            name="bedtime",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="learning_style",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentassessment",
            name="wakeup_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_style",
                    models.CharField(
                        choices=[
                            ("visual", "Visual"),
                            ("auditory", "Auditory"),
                            ("kinesthetic", "Hands-on"),
                        ],
                        default="visual",
                        max_length=20,
                    ),
                ),
                ("academic_goals", models.TextField(blank=True)),
                ("wakeup_time", models.TimeField(default="07:00")),
                ("bedtime", models.TimeField(default="22:00")),
                ("strengths", models.CharField(blank=True, max_length=100)),
                ("weaknesses", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
