# Generated by Django 5.1.7 on 2025-04-09 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictor", "0003_chatinteraction_is_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Font Awesome icon class", max_length=50
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chatinteraction",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="predictor.subject",
            ),
        ),
    ]
